version: '3.7'
services:
  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 80:80
      - 27017:27017
    volumes:
      - ./mongoDB/:/data/db

